// Search keywords for emojis used in EmojiPicker.
// Hand-curated; English only for now. Indonesian search can be added later.
// Default-exported so EmojiPicker can dynamic-import it (keeps initial bundle clean).

const EMOJI_KEYWORDS: Record<string, string[]> = {
  // Faces
  '😀': ['grin', 'happy', 'smile', 'face'],
  '😃': ['smile', 'happy', 'open mouth', 'face'],
  '😄': ['smile', 'happy', 'joy', 'face'],
  '😁': ['beam', 'grin', 'smile', 'face'],
  '😆': ['laugh', 'satisfied', 'face'],
  '😅': ['sweat', 'laugh', 'relief', 'face'],
  '🤣': ['rofl', 'laugh', 'rolling', 'face'],
  '😂': ['joy', 'laugh', 'cry', 'tears', 'face'],
  '🙂': ['slight smile', 'face'],
  '😊': ['blush', 'smile', 'happy', 'face'],
  '😇': ['angel', 'halo', 'innocent', 'face'],
  '🥰': ['love', 'hearts', 'adore', 'face'],
  '😍': ['heart eyes', 'love', 'face'],
  '🤩': ['star eyes', 'starstruck', 'face'],
  '😘': ['kiss', 'blow kiss', 'face'],
  '😗': ['kiss', 'face'],
  '😚': ['kiss', 'closed eyes', 'face'],
  '😙': ['kiss', 'smile', 'face'],
  '🥲': ['smile tear', 'happy cry', 'face'],
  '😋': ['yum', 'tasty', 'tongue', 'face'],
  '😛': ['tongue', 'silly', 'face'],
  '😜': ['wink', 'tongue', 'silly', 'face'],
  '🤪': ['zany', 'crazy', 'silly', 'face'],
  '😝': ['tongue', 'closed eyes', 'face'],
  '🤑': ['money', 'rich', 'face'],
  '🤗': ['hug', 'embrace', 'face'],
  '🤭': ['oops', 'giggle', 'shy', 'face'],
  '🤫': ['shush', 'quiet', 'silent', 'face'],
  '🤔': ['think', 'thinking', 'face'],
  '🫡': ['salute', 'face'],
  '🤐': ['zip', 'silent', 'face'],
  '🤨': ['raised eyebrow', 'skeptic', 'face'],
  '😐': ['neutral', 'face'],
  '😑': ['expressionless', 'face'],
  '😶': ['no mouth', 'silent', 'face'],
  '🫥': ['dotted', 'invisible', 'face'],
  '😏': ['smirk', 'face'],
  '😒': ['unamused', 'face'],
  '🙄': ['eye roll', 'face'],
  '😬': ['grimace', 'awkward', 'face'],
  '🤥': ['lying', 'pinocchio', 'face'],
  '😌': ['relieved', 'calm', 'face'],
  '😔': ['pensive', 'sad', 'face'],
  '😪': ['sleepy', 'tired', 'face'],
  '🤤': ['drool', 'face'],
  '😴': ['sleep', 'snore', 'tired', 'face'],
  '😷': ['mask', 'sick', 'face'],
  '🤒': ['fever', 'sick', 'thermometer', 'face'],
  '🤕': ['bandage', 'hurt', 'face'],
  '🤢': ['nausea', 'sick', 'face'],
  '🤮': ['vomit', 'sick', 'face'],
  '🥵': ['hot', 'sweat', 'face'],
  '🥶': ['cold', 'freezing', 'face'],
  '🥴': ['woozy', 'drunk', 'face'],
  '😵': ['dizzy', 'face'],
  '🤯': ['mind blown', 'shocked', 'face'],
  '🤠': ['cowboy', 'face'],
  '🥳': ['party', 'celebrate', 'face'],
  '🥸': ['disguise', 'face'],
  '😎': ['cool', 'sunglasses', 'face'],
  '🤓': ['nerd', 'glasses', 'face'],
  '🧐': ['monocle', 'face'],
  '😕': ['confused', 'face'],
  '🫤': ['diagonal mouth', 'face'],
  '😟': ['worried', 'face'],
  '🙁': ['frown', 'sad', 'face'],
  '😮': ['open mouth', 'wow', 'face'],
  '😯': ['hushed', 'face'],
  '😲': ['astonished', 'shocked', 'face'],
  '😳': ['flushed', 'embarrassed', 'face'],
  '🥺': ['pleading', 'puppy eyes', 'face'],
  '🥹': ['holding back tears', 'face'],
  '😦': ['frown open', 'face'],
  '😧': ['anguished', 'face'],
  '😨': ['fearful', 'scared', 'face'],
  '😰': ['anxious', 'sweat', 'face'],
  '😥': ['sad relief', 'face'],
  '😢': ['cry', 'tear', 'sad', 'face'],
  '😭': ['sob', 'cry', 'sad', 'face'],
  '😱': ['scream', 'fear', 'shock', 'face'],
  '😖': ['confounded', 'face'],
  '😣': ['persevering', 'face'],
  '😞': ['disappointed', 'sad', 'face'],
  '😓': ['sweat', 'down', 'face'],
  '😩': ['weary', 'tired', 'face'],
  '😫': ['tired', 'exhausted', 'face'],
  '🥱': ['yawn', 'tired', 'face'],
  '😤': ['huff', 'frustrated', 'face'],
  '😡': ['rage', 'angry', 'mad', 'face'],
  '😠': ['angry', 'mad', 'face'],
  '🤬': ['cursing', 'angry', 'swear', 'face'],
  '😈': ['devil smile', 'imp', 'face'],
  '👿': ['devil angry', 'imp', 'face'],
  '💀': ['skull', 'death'],
  '☠️': ['skull crossbones', 'death', 'poison'],
  '💩': ['poop', 'pile'],
  '🤡': ['clown', 'face'],
  '👹': ['ogre', 'monster'],
  '👺': ['goblin', 'monster'],
  '👻': ['ghost', 'spooky'],
  '👽': ['alien', 'space'],
  '👾': ['alien monster', 'space'],
  '🤖': ['robot', 'bot'],
  '🎃': ['pumpkin', 'halloween', 'jack'],
  '😺': ['cat smile', 'face'],
  '😸': ['cat grin', 'face'],
  '😹': ['cat joy', 'tears', 'face'],
  '😻': ['cat heart eyes', 'love', 'face'],
  '😼': ['cat smirk', 'face'],
  '😽': ['cat kiss', 'face'],
  '🙀': ['cat scream', 'face'],
  '😿': ['cat cry', 'sad', 'face'],
  '😾': ['cat pout', 'angry', 'face'],

  // Hands
  '👋': ['wave', 'hi', 'hello', 'bye', 'hand'],
  '🤚': ['raised back hand', 'hand'],
  '🖐️': ['hand splayed', 'fingers', 'hand'],
  '✋': ['raised hand', 'stop', 'hand'],
  '🖖': ['vulcan', 'spock', 'hand'],
  '🫱': ['rightwards hand', 'shake', 'hand'],
  '🫲': ['leftwards hand', 'shake', 'hand'],
  '🫳': ['palm down', 'hand'],
  '🫴': ['palm up', 'hand'],
  '🫷': ['leftward push', 'hand'],
  '🫸': ['rightward push', 'hand'],
  '👌': ['ok', 'okay', 'hand'],
  '🤌': ['pinched fingers', 'italian', 'hand'],
  '🤏': ['pinch', 'small', 'hand'],
  '✌️': ['victory', 'peace', 'hand'],
  '🤞': ['fingers crossed', 'luck', 'hand'],
  '🫰': ['heart fingers', 'hand'],
  '🤟': ['love you', 'rock', 'hand'],
  '🤘': ['rock on', 'horns', 'hand'],
  '🤙': ['call me', 'shaka', 'hand'],
  '👈': ['point left', 'hand'],
  '👉': ['point right', 'hand'],
  '👆': ['point up', 'hand'],
  '🖕': ['middle finger', 'hand'],
  '👇': ['point down', 'hand'],
  '☝️': ['index up', 'hand'],
  '🫵': ['point at viewer', 'you', 'hand'],
  '👍': ['thumbs up', 'like', 'good', 'yes', 'hand'],
  '👎': ['thumbs down', 'dislike', 'bad', 'no', 'hand'],
  '✊': ['fist', 'hand'],
  '👊': ['punch', 'fist bump', 'hand'],
  '🤛': ['fist left', 'hand'],
  '🤜': ['fist right', 'hand'],
  '👏': ['clap', 'applause', 'hand'],
  '🙌': ['raised hands', 'celebrate', 'praise', 'hand'],
  '🫶': ['heart hands', 'love', 'hand'],
  '👐': ['open hands', 'hand'],
  '🤲': ['palms up', 'pray', 'hand'],
  '🤝': ['handshake', 'deal', 'hand'],
  '🙏': ['pray', 'thanks', 'please', 'hand'],
  '✍️': ['writing', 'hand', 'pen'],
  '💅': ['nail polish', 'manicure', 'hand'],
  '🤳': ['selfie', 'hand', 'phone'],
  '💪': ['muscle', 'flex', 'strong', 'arm', 'fitness', 'workout', 'gym'],
  '🦾': ['mechanical arm', 'prosthetic', 'arm'],
  '🦿': ['mechanical leg', 'prosthetic', 'leg'],
  '🦵': ['leg'],
  '🦶': ['foot'],
  '👂': ['ear'],
  '🦻': ['hearing aid', 'ear'],
  '👃': ['nose'],
  '👁️': ['eye'],
  '👀': ['eyes', 'look'],
  '🫀': ['anatomical heart', 'organ'],
  '🫁': ['lungs', 'organ', 'breath'],
  '🧠': ['brain', 'mind', 'organ', 'think'],
  '🦷': ['tooth', 'dental'],
  '🦴': ['bone', 'skeleton'],

  // Fitness
  '🏃': ['run', 'running', 'jog', 'cardio', 'fitness'],
  '🚴': ['bike', 'cycle', 'cycling', 'fitness'],
  '🏋️': ['lift', 'weight', 'gym', 'fitness'],
  '🧘': ['yoga', 'meditate', 'zen', 'mindful', 'fitness'],
  '🤸': ['cartwheel', 'gymnastics', 'fitness'],
  '⛹️': ['basketball', 'bounce', 'fitness'],
  '🏊': ['swim', 'pool', 'fitness'],
  '🥊': ['boxing', 'glove', 'fight', 'fitness'],
  '🎯': ['target', 'goal', 'aim', 'darts'],
  '🏄': ['surf', 'wave', 'fitness'],
  '🧗': ['climb', 'rock', 'fitness'],
  '🤾': ['handball', 'fitness'],
  '🏇': ['horse riding', 'jockey', 'fitness'],
  '⚽': ['soccer', 'football', 'sport'],
  '🏀': ['basketball', 'sport'],
  '🏈': ['american football', 'sport'],
  '🎾': ['tennis', 'sport'],
  '🏐': ['volleyball', 'sport'],
  '🏓': ['ping pong', 'table tennis', 'sport'],
  '🏸': ['badminton', 'sport'],
  '⛷️': ['ski', 'snow', 'sport'],
  '🛹': ['skateboard', 'sport'],
  '🤿': ['diving', 'snorkel', 'sport'],
  '🚣': ['row', 'boat', 'sport'],
  '⚾': ['baseball', 'sport'],
  '🥋': ['martial arts', 'karate', 'gi', 'sport'],
  '🤼': ['wrestle', 'sport'],
  '🏌️': ['golf', 'sport'],
  '🎿': ['skis', 'snow', 'sport'],
  '🛷': ['sled', 'snow', 'sport'],
  '⛸️': ['ice skate', 'sport'],
  '🥏': ['frisbee', 'flying disc', 'sport'],
  '🤺': ['fence', 'sword', 'sport'],
  '🏑': ['hockey', 'field', 'sport'],
  '🥅': ['goal', 'net', 'sport'],
  '⛳': ['flag in hole', 'golf', 'sport'],
  '🪃': ['boomerang', 'throw'],
  '🛼': ['roller skate', 'sport'],
  '🧗‍♀️': ['woman climbing', 'climb', 'sport'],
  '🧗‍♂️': ['man climbing', 'climb', 'sport'],
  '🏊‍♀️': ['woman swim', 'sport'],
  '🏊‍♂️': ['man swim', 'sport'],
  '🚶': ['walk', 'walking', 'fitness'],
  '🚶‍♀️': ['woman walk', 'walking'],
  '🧎': ['kneel', 'kneeling'],

  // Health
  '💤': ['sleep', 'zzz', 'rest', 'tired'],
  '💧': ['water', 'drop', 'hydrate', 'drink'],
  '❤️': ['heart', 'love', 'red'],
  '🩷': ['pink heart', 'love'],
  '🧡': ['orange heart', 'love'],
  '💛': ['yellow heart', 'love'],
  '💚': ['green heart', 'love'],
  '💙': ['blue heart', 'love'],
  '🩵': ['light blue heart', 'love'],
  '💜': ['purple heart', 'love'],
  '🤍': ['white heart', 'love'],
  '🖤': ['black heart', 'love'],
  '🩺': ['stethoscope', 'doctor', 'medic', 'health'],
  '🌡️': ['thermometer', 'temperature', 'fever', 'health'],
  '🧬': ['dna', 'genetic', 'biology', 'health'],
  '🩸': ['blood', 'drop', 'health'],
  '🤧': ['sneeze', 'sick', 'cold', 'health'],
  '🩹': ['bandage', 'plaster', 'health'],
  '🧴': ['lotion', 'bottle', 'sunscreen', 'skincare', 'cream'],
  '🧼': ['soap', 'wash', 'clean', 'skincare'],
  '🪥': ['toothbrush', 'dental', 'hygiene'],
  '🛁': ['bath', 'tub', 'wash'],
  '🚿': ['shower', 'wash'],
  '🩻': ['xray', 'x-ray', 'medical', 'health'],
  '💉': ['syringe', 'shot', 'vaccine', 'injection', 'health'],
  '🧪': ['test tube', 'lab', 'science'],
  '🩼': ['crutch', 'medical'],
  '♿': ['wheelchair', 'accessible'],
  '🏥': ['hospital', 'medical'],
  '🚑': ['ambulance', 'emergency', 'medical'],
  '⚕️': ['medical', 'caduceus', 'health'],
  '🔬': ['microscope', 'science', 'lab'],
  '💊': ['pill', 'medicine', 'medication', 'drug', 'supplement', 'health', 'vitamin'],

  // Food
  '🥗': ['salad', 'greens', 'healthy', 'food'],
  '🍎': ['apple', 'red', 'fruit', 'food'],
  '🥦': ['broccoli', 'vegetable', 'green', 'food'],
  '🍳': ['egg', 'fried', 'breakfast', 'food'],
  '🥤': ['cup', 'soda', 'drink', 'beverage'],
  '☕': ['coffee', 'caffeine', 'drink', 'beverage'],
  '🍵': ['tea', 'matcha', 'drink', 'beverage'],
  '🫖': ['teapot', 'tea', 'drink'],
  '🥛': ['milk', 'glass', 'drink', 'beverage'],
  '🍌': ['banana', 'fruit', 'food', 'yellow'],
  '🍇': ['grape', 'fruit', 'food'],
  '🍊': ['orange', 'tangerine', 'citrus', 'fruit', 'food'],
  '🍋': ['lemon', 'citrus', 'fruit', 'food'],
  '🍉': ['watermelon', 'fruit', 'food'],
  '🍓': ['strawberry', 'fruit', 'berry', 'food'],
  '🫐': ['blueberry', 'berry', 'fruit', 'food'],
  '🍑': ['peach', 'fruit', 'food'],
  '🥭': ['mango', 'fruit', 'food'],
  '🍍': ['pineapple', 'fruit', 'food'],
  '🥥': ['coconut', 'fruit', 'food'],
  '🥑': ['avocado', 'fruit', 'food'],
  '🫒': ['olive', 'oil', 'food', 'mediterranean'],
  '🍆': ['eggplant', 'aubergine', 'vegetable', 'food'],
  '🥕': ['carrot', 'vegetable', 'food'],
  '🌽': ['corn', 'vegetable', 'food'],
  '🥒': ['cucumber', 'vegetable', 'food'],
  '🥬': ['leafy green', 'lettuce', 'vegetable', 'food'],
  '🫑': ['bell pepper', 'capsicum', 'vegetable', 'food'],
  '🌶️': ['hot pepper', 'chili', 'spicy', 'vegetable', 'food'],
  '🧄': ['garlic', 'food'],
  '🧅': ['onion', 'vegetable', 'food'],
  '🥔': ['potato', 'vegetable', 'food'],
  '🍠': ['sweet potato', 'roasted', 'vegetable', 'food'],
  '🍄': ['mushroom', 'food'],
  '🥜': ['peanut', 'nut', 'food'],
  '🌰': ['chestnut', 'nut', 'acorn', 'food'],
  '🫘': ['beans', 'legume', 'food', 'protein'],
  '🫛': ['pea pod', 'peas', 'vegetable', 'food'],
  '🫚': ['ginger', 'root', 'spice', 'food'],
  '🍞': ['bread', 'loaf', 'food'],
  '🥯': ['bagel', 'bread', 'food'],
  '🥚': ['egg', 'food'],
  '🧀': ['cheese', 'food'],
  '🥩': ['steak', 'meat', 'beef', 'food'],
  '🍗': ['poultry leg', 'chicken', 'meat', 'food'],
  '🍖': ['meat bone', 'food'],
  '🌮': ['taco', 'mexican', 'food'],
  '🍕': ['pizza', 'food'],
  '🍜': ['noodles', 'ramen', 'food'],
  '🍲': ['pot of food', 'stew', 'soup', 'food'],
  '🥘': ['paella', 'food'],
  '🍱': ['bento', 'lunch box', 'japanese', 'food'],
  '🍙': ['rice ball', 'onigiri', 'food'],
  '🍚': ['rice', 'food'],
  '🥮': ['mooncake', 'food'],
  '🧁': ['cupcake', 'sweet', 'dessert', 'food'],
  '🍰': ['cake', 'shortcake', 'sweet', 'dessert', 'food'],
  '🍫': ['chocolate', 'sweet', 'food'],
  '🍿': ['popcorn', 'snack', 'food'],
  '🍔': ['burger', 'hamburger', 'food'],
  '🌯': ['burrito', 'wrap', 'food'],
  '🥙': ['stuffed flatbread', 'food'],
  '🧆': ['falafel', 'food'],
  '🥫': ['canned food', 'food'],
  '🫕': ['fondue', 'food'],
  '🍝': ['spaghetti', 'pasta', 'food'],
  '🍛': ['curry', 'rice', 'food'],
  '🍣': ['sushi', 'japanese', 'food'],
  '🍤': ['shrimp', 'tempura', 'food'],
  '🍥': ['fish cake', 'narutomaki', 'food'],
  '🥟': ['dumpling', 'food'],
  '🥠': ['fortune cookie', 'food'],
  '🥡': ['takeout box', 'food', 'lunch'],
  '🍡': ['dango', 'sweet', 'food'],
  '🍢': ['oden', 'skewer', 'food'],
  '🍧': ['shaved ice', 'dessert', 'food'],
  '🍨': ['ice cream', 'dessert', 'food'],
  '🍦': ['soft serve', 'ice cream', 'dessert', 'food'],
  '🎂': ['birthday cake', 'celebrate', 'food'],
  '🍮': ['custard', 'pudding', 'dessert', 'food'],
  '🍯': ['honey', 'pot', 'food'],
  '🍬': ['candy', 'sweet', 'food'],
  '🍭': ['lollipop', 'sweet', 'food'],
  '🍩': ['donut', 'doughnut', 'sweet', 'food'],
  '🍪': ['cookie', 'biscuit', 'food'],
  '🥧': ['pie', 'dessert', 'food'],
  '🧇': ['waffle', 'food'],
  '🥞': ['pancakes', 'breakfast', 'food'],
  '🧈': ['butter', 'food'],
  '🥐': ['croissant', 'pastry', 'food'],
  '🥖': ['baguette', 'bread', 'food'],
  '🫓': ['flatbread', 'food'],
  '🥨': ['pretzel', 'food'],
  '🫙': ['jar', 'container', 'food'],
  '🧃': ['juice box', 'drink', 'beverage'],
  '🧊': ['ice', 'cube', 'cold', 'frozen'],
  '🥂': ['champagne', 'cheers', 'drink'],
  '🍷': ['wine', 'red wine', 'drink'],
  '🍺': ['beer', 'drink'],
  '🍸': ['cocktail', 'martini', 'drink'],
  '🍹': ['tropical drink', 'cocktail', 'drink'],
  '🫗': ['pouring liquid', 'drink'],
  '🥃': ['whiskey', 'tumbler', 'drink'],
  '🧋': ['bubble tea', 'boba', 'drink'],
  '🧉': ['mate', 'drink'],

  // Mind
  '📖': ['book open', 'read', 'study'],
  '🎵': ['music note', 'song', 'sound'],
  '🧩': ['puzzle', 'jigsaw', 'piece'],
  '🎨': ['art', 'paint', 'palette'],
  '📝': ['memo', 'note', 'write', 'pencil'],
  '🌅': ['sunrise', 'morning', 'sun'],
  '🌙': ['crescent moon', 'night', 'moon'],
  '🎹': ['piano', 'music', 'keys'],
  '🎸': ['guitar', 'music'],
  '🎺': ['trumpet', 'music', 'brass'],
  '🥁': ['drum', 'music', 'beat'],
  '🎭': ['theater', 'masks', 'drama'],
  '🎬': ['clapper', 'movie', 'film'],
  '📷': ['camera', 'photo'],
  '🎮': ['game controller', 'video game', 'play'],
  '♟️': ['chess', 'pawn', 'strategy'],
  '🧶': ['yarn', 'knit'],
  '🪡': ['needle', 'sew'],
  '🖌️': ['paintbrush', 'art'],
  '✏️': ['pencil', 'write'],
  '📓': ['notebook', 'journal'],
  '🔮': ['crystal ball', 'magic', 'fortune'],
  '🕯️': ['candle', 'light', 'flame'],
  '🧘‍♀️': ['woman meditate', 'yoga'],
  '🧘‍♂️': ['man meditate', 'yoga'],
  '🪷': ['lotus', 'flower', 'meditate'],
  '☮️': ['peace sign'],
  '🫧': ['bubbles'],
  '💭': ['thought bubble', 'think'],
  '💡': ['idea', 'lightbulb', 'bright'],
  '🌈': ['rainbow', 'colors'],
  '🎤': ['microphone', 'mic', 'sing', 'karaoke'],
  '🎧': ['headphones', 'music', 'listen'],
  '🎻': ['violin', 'music', 'string'],
  '🪘': ['long drum', 'music'],
  '🪗': ['accordion', 'music'],
  '🎷': ['saxophone', 'sax', 'music'],
  '📚': ['books', 'library', 'study', 'read'],
  '📰': ['newspaper', 'news'],
  '🖊️': ['pen', 'write'],
  '🖋️': ['fountain pen', 'write'],
  '📔': ['notebook decorated', 'journal'],
  '📕': ['red book', 'closed book', 'read'],
  '📗': ['green book', 'read'],
  '📘': ['blue book', 'read'],
  '📙': ['orange book', 'read'],
  '🔍': ['search', 'magnify', 'look', 'find'],
  '🧿': ['nazar', 'evil eye', 'amulet'],
  '🪬': ['hamsa', 'amulet'],
  '🎲': ['dice', 'game', 'random'],
  '🧸': ['teddy bear', 'plush', 'toy'],
  '🪆': ['matryoshka', 'nesting doll'],
  '🎪': ['circus', 'tent'],
  '🎠': ['carousel', 'horse'],
  '🎡': ['ferris wheel'],
  '🎢': ['roller coaster'],

  // Productivity
  '⭐': ['star', 'favorite'],
  '🚀': ['rocket', 'launch', 'fast'],
  '💻': ['laptop', 'computer'],
  '🗂️': ['card index', 'folders', 'organize'],
  '⏰': ['alarm clock', 'time'],
  '📧': ['email', 'mail', 'envelope'],
  '🔔': ['bell', 'notification', 'alert'],
  '✅': ['check', 'done', 'tick', 'complete'],
  '🏆': ['trophy', 'win', 'award'],
  '📊': ['bar chart', 'graph', 'data'],
  '📈': ['chart up', 'increase', 'growth'],
  '🗓️': ['calendar', 'date', 'schedule'],
  '📋': ['clipboard', 'list'],
  '🎒': ['backpack', 'bag', 'school'],
  '💼': ['briefcase', 'work', 'business'],
  '🖥️': ['desktop', 'computer'],
  '⌨️': ['keyboard', 'type'],
  '🖱️': ['mouse', 'computer'],
  '📱': ['phone', 'mobile', 'cell'],
  '⏳': ['hourglass', 'time', 'wait'],
  '🔑': ['key', 'unlock'],
  '🔒': ['lock', 'secure'],
  '🛠️': ['tools', 'hammer wrench', 'fix'],
  '⚙️': ['gear', 'settings', 'cog'],
  '🧰': ['toolbox', 'tools'],
  '📌': ['pin', 'pushpin'],
  '🏅': ['medal', 'award'],
  '🥇': ['gold medal', 'first', 'win'],
  '🥈': ['silver medal', 'second'],
  '🎖️': ['military medal', 'honor'],
  '💎': ['gem', 'diamond', 'jewel'],
  '🔥': ['fire', 'hot', 'lit', 'flame'],
  '⚡': ['lightning', 'bolt', 'fast', 'energy'],
  '🗃️': ['card box', 'archive'],
  '📎': ['paperclip', 'attach'],
  '📐': ['triangular ruler', 'measure'],
  '📏': ['ruler', 'measure', 'straight'],
  '🗑️': ['trash', 'bin', 'delete'],
  '📤': ['outbox', 'send'],
  '📥': ['inbox', 'receive'],
  '📬': ['mailbox', 'mail'],
  '📭': ['mailbox empty'],
  '🗳️': ['ballot', 'vote'],
  '🔏': ['locked pen'],
  '🔐': ['locked key'],
  '🔓': ['unlocked'],
  '🪪': ['id card', 'identification'],
  '💳': ['credit card', 'pay'],
  '🧮': ['abacus', 'calculate'],
  '📡': ['satellite', 'antenna', 'signal'],
  '🔋': ['battery', 'power'],
  '💾': ['floppy', 'save', 'disk'],
  '💿': ['cd', 'disc'],
  '🖨️': ['printer'],
  '📠': ['fax'],

  // Social
  '💬': ['speech bubble', 'chat', 'talk'],
  '📞': ['phone', 'call'],
  '👨‍👩‍👧': ['family', 'parents girl'],
  '❤️‍🔥': ['heart on fire', 'love'],
  '🎉': ['party popper', 'celebrate', 'tada'],
  '📸': ['camera flash', 'photo'],
  '🌍': ['earth', 'world', 'globe'],
  '🎊': ['confetti', 'celebrate'],
  '🎁': ['gift', 'present'],
  '🎈': ['balloon', 'celebrate'],
  '💌': ['love letter'],
  '💕': ['two hearts', 'love'],
  '👫': ['couple', 'partners'],
  '👭': ['two women', 'partners'],
  '👬': ['two men', 'partners'],
  '🫂': ['people hugging', 'support'],
  '💝': ['heart with ribbon', 'love'],
  '🎆': ['fireworks', 'celebrate'],
  '👨‍👩‍👦': ['family boy'],
  '👨‍👩‍👧‍👦': ['family kids'],
  '👪': ['family'],
  '👶': ['baby', 'infant'],
  '🧒': ['child'],
  '👦': ['boy'],
  '👧': ['girl'],
  '👨': ['man'],
  '👩': ['woman'],
  '🧑': ['person'],
  '👴': ['old man', 'grandpa'],
  '👵': ['old woman', 'grandma'],
  '🧓': ['older person'],
  '💏': ['kiss couple'],
  '💑': ['couple heart'],
  '👰': ['bride', 'wedding'],
  '🤵': ['groom', 'tuxedo', 'wedding'],
  '🎅': ['santa', 'christmas'],
  '🤶': ['mrs claus', 'christmas'],
  '🧑‍🎄': ['mx claus', 'christmas'],
  '🦸': ['superhero'],
  '🦹': ['supervillain'],
  '🧙': ['mage', 'wizard'],
  '🧚': ['fairy'],
  '🧜': ['mermaid'],
  '🧝': ['elf'],

  // Nature
  '🌳': ['tree', 'deciduous'],
  '🌲': ['evergreen', 'pine', 'tree'],
  '🌱': ['seedling', 'sprout', 'plant', 'grow'],
  '🪴': ['potted plant', 'houseplant', 'plant'],
  '🌼': ['daisy', 'blossom', 'flower'],
  '🪻': ['hyacinth', 'flower', 'purple'],
  '🪲': ['beetle', 'bug', 'insect'],
  '🪱': ['worm', 'earthworm'],
  '🪼': ['jellyfish', 'sea'],
  '🌿': ['herb', 'leaf'],
  '🌸': ['cherry blossom', 'pink', 'flower'],
  '☀️': ['sun', 'sunny'],
  '🌊': ['wave', 'water', 'ocean'],
  '🐕': ['dog', 'pet'],
  '🐈': ['cat', 'pet'],
  '🦅': ['eagle', 'bird'],
  '🌻': ['sunflower', 'yellow'],
  '🍃': ['leaves', 'wind'],
  '🌺': ['hibiscus', 'flower'],
  '🌹': ['rose', 'flower', 'red'],
  '🌷': ['tulip', 'flower'],
  '💐': ['bouquet', 'flowers'],
  '🌾': ['rice plant', 'grain'],
  '🍀': ['four leaf clover', 'lucky'],
  '🍁': ['maple leaf', 'autumn'],
  '🍂': ['fallen leaf', 'autumn'],
  '🌴': ['palm tree', 'tropical'],
  '🎋': ['tanabata tree'],
  '🌵': ['cactus'],
  '🐶': ['dog face', 'puppy', 'pet'],
  '🐱': ['cat face', 'kitten', 'pet'],
  '🐰': ['rabbit', 'bunny'],
  '🐻': ['bear'],
  '🦊': ['fox'],
  '🐼': ['panda'],
  '🐨': ['koala'],
  '🦁': ['lion'],
  '🐯': ['tiger'],
  '🐸': ['frog'],
  '🦋': ['butterfly'],
  '🐝': ['bee', 'honey'],
  '🐞': ['ladybug', 'beetle'],
  '🌎': ['earth americas', 'world', 'globe'],
  '🏔️': ['mountain snow'],
  '🏖️': ['beach'],
  '⛰️': ['mountain'],
  '🌄': ['mountain sunrise'],
  '🌠': ['shooting star'],
  '🌤️': ['sun behind cloud'],
  '🌧️': ['rain cloud', 'rain'],
  '🐔': ['chicken', 'hen'],
  '🐧': ['penguin'],
  '🐦': ['bird'],
  '🐤': ['baby chick', 'bird'],
  '🦆': ['duck'],
  '🦉': ['owl'],
  '🦇': ['bat'],
  '🐺': ['wolf'],
  '🐗': ['boar'],
  '🐴': ['horse'],
  '🦄': ['unicorn'],
  '🐛': ['bug', 'caterpillar'],
  '🐌': ['snail'],
  '🐙': ['octopus'],
  '🦑': ['squid'],
  '🐠': ['tropical fish'],
  '🐟': ['fish'],
  '🐬': ['dolphin'],
  '🐳': ['whale'],
  '🦈': ['shark'],
  '🐊': ['crocodile'],
  '🐢': ['turtle'],
  '🐍': ['snake'],
  '🦎': ['lizard'],
  '🦕': ['sauropod', 'dinosaur'],
  '🦖': ['t-rex', 'dinosaur'],
  '🐘': ['elephant'],
  '🦏': ['rhino', 'rhinoceros'],
  '🦛': ['hippo'],
  '🐪': ['camel'],
  '🦒': ['giraffe'],
  '🦘': ['kangaroo'],
  '🦬': ['bison', 'buffalo'],
  '🐃': ['water buffalo'],
  '🐂': ['ox'],
  '🐄': ['cow'],
  '🐎': ['horse running'],
  '🐑': ['sheep'],
  '🐐': ['goat'],
  '🦌': ['deer'],
  '🐿️': ['chipmunk', 'squirrel'],
  '🦔': ['hedgehog'],
  '🐇': ['rabbit running'],
  '🦝': ['raccoon'],
  '🦫': ['beaver'],
  '🦨': ['skunk'],
  '🦡': ['badger'],
  '🐁': ['mouse'],
  '🐀': ['rat'],
  '🐓': ['rooster'],
  '🦃': ['turkey'],
  '🦚': ['peacock'],
  '🦜': ['parrot'],
  '🪿': ['goose'],
  '🐦‍⬛': ['black bird'],
  '🕊️': ['dove', 'peace'],
  '🦩': ['flamingo'],
  '🪺': ['nest with eggs'],

  // Symbols
  '❌': ['cross', 'no', 'wrong', 'x'],
  '🚫': ['no entry', 'prohibited', 'forbidden'],
  '⭕': ['heavy circle', 'o', 'correct'],
  '❗': ['exclamation', 'alert'],
  '❓': ['question', 'help'],
  '❕': ['white exclamation'],
  '❔': ['white question'],
  '‼️': ['double exclamation'],
  '⁉️': ['exclamation question'],
  '✖️': ['multiply', 'cross', 'x'],
  '➕': ['plus', 'add'],
  '➖': ['minus', 'subtract'],
  '➗': ['divide'],
  '♾️': ['infinity'],
  '💲': ['dollar sign'],
  '💱': ['currency exchange'],
  '™️': ['trademark'],
  '©️': ['copyright'],
  '®️': ['registered'],
  '〰️': ['wavy dash'],
  '➰': ['curly loop'],
  '➿': ['double curly loop'],
  '✔️': ['check mark', 'tick', 'done'],
  '☑️': ['check box', 'tick'],
  '🔘': ['radio button'],
  '🔴': ['red circle'],
  '🟠': ['orange circle'],
  '🟡': ['yellow circle'],
  '🟢': ['green circle'],
  '🔵': ['blue circle'],
  '🟣': ['purple circle'],
  '⚫': ['black circle'],
  '⚪': ['white circle'],
  '🟤': ['brown circle'],
  '🔺': ['red triangle up'],
  '🔻': ['red triangle down'],
  '🔸': ['orange diamond small'],
  '🔹': ['blue diamond small'],
  '🔶': ['orange diamond large'],
  '🔷': ['blue diamond large'],
  '💠': ['diamond shape'],
  '🔳': ['white square button'],
  '🔲': ['black square button'],
  '🟥': ['red square'],
  '🟧': ['orange square'],
  '🟨': ['yellow square'],
  '🟩': ['green square'],
  '🟦': ['blue square'],
  '🟪': ['purple square'],
  '⬛': ['black square'],
  '⬜': ['white square'],
  '🟫': ['brown square'],
  '♠️': ['spade'],
  '♥️': ['heart suit'],
  '♦️': ['diamond suit'],
  '♣️': ['club'],
  '🃏': ['joker', 'card'],
  '🀄': ['mahjong', 'red dragon'],
  '🎴': ['flower playing cards'],
  '💯': ['100', 'hundred', 'perfect'],
  '🔅': ['low brightness'],
  '🔆': ['high brightness'],
  '🔈': ['speaker low'],
  '🔇': ['mute', 'silent'],
  '🔉': ['speaker medium'],
  '🔊': ['speaker high', 'loud'],
  '🔕': ['no bell'],
  '📣': ['megaphone', 'announce'],
  '📢': ['loudspeaker'],
  '🗯️': ['anger bubble'],
  '♻️': ['recycle', 'reuse'],
  '⚜️': ['fleur de lis'],
  '🔰': ['japanese symbol beginner'],
  '🔱': ['trident'],
  '🌟': ['glowing star'],
  '💫': ['dizzy star'],
  '✨': ['sparkles', 'shiny'],
  '💥': ['boom', 'explode'],
  '☄️': ['comet'],
  '🎶': ['multiple notes', 'music'],
  '🏳️': ['white flag'],
  '🏴': ['black flag'],
  '🏁': ['checkered flag'],
  '🚩': ['triangular flag', 'red flag'],
  '🏳️‍🌈': ['rainbow flag', 'pride'],
  '🏳️‍⚧️': ['transgender flag'],
  '⚠️': ['warning', 'caution'],
  '🚸': ['children crossing'],
  '⛔': ['no entry'],
  '🚳': ['no bicycles'],
  '🚭': ['no smoking'],
  '🚯': ['no littering'],
  '🚱': ['non potable water'],
  '🚷': ['no pedestrians'],
  '📵': ['no phones'],
  '🔞': ['no minors', '18'],
  '☢️': ['radioactive'],
  '☣️': ['biohazard'],
  '🛑': ['stop sign'],
  '⛎': ['ophiuchus'],
  '♈': ['aries', 'zodiac'],
  '♉': ['taurus', 'zodiac'],
  '♊': ['gemini', 'zodiac'],
  '♋': ['cancer', 'zodiac'],
  '♌': ['leo', 'zodiac'],
  '♍': ['virgo', 'zodiac'],
  '♎': ['libra', 'zodiac'],
  '♏': ['scorpio', 'zodiac'],
  '♐': ['sagittarius', 'zodiac'],
  '♑': ['capricorn', 'zodiac'],
  '♒': ['aquarius', 'zodiac'],
  '♓': ['pisces', 'zodiac'],

  // Objects
  '⌚': ['watch', 'time'],
  '🪤': ['mouse trap'],
  '🔦': ['flashlight', 'torch'],
  '🧯': ['fire extinguisher'],
  '🛢️': ['oil drum'],
  '💸': ['money flying', 'cash'],
  '💵': ['dollar', 'cash'],
  '💴': ['yen'],
  '💶': ['euro'],
  '💷': ['pound'],
  '🪙': ['coin'],
  '💰': ['money bag'],
  '🧲': ['magnet'],
  '🪜': ['ladder'],
  '🧱': ['brick'],
  '🪵': ['wood log'],
  '🪨': ['rock', 'stone'],
  '🛡️': ['shield'],
  '🗡️': ['dagger', 'knife', 'sword'],
  '⚔️': ['crossed swords'],
  '🔫': ['water pistol', 'gun'],
  '🏹': ['bow arrow'],
  '🔧': ['wrench', 'tool'],
  '🪛': ['screwdriver', 'tool'],
  '🔩': ['nut bolt'],
  '🪚': ['saw'],
  '🔨': ['hammer', 'tool'],
  '⛏️': ['pick'],
  '⚒️': ['hammer pick'],
  '🪝': ['hook'],
  '🪣': ['bucket'],
  '⚗️': ['alembic', 'chemistry'],
  '🧫': ['petri dish'],
  '🔭': ['telescope', 'astronomy'],
  '🚪': ['door'],
  '🪞': ['mirror'],
  '🪟': ['window'],
  '🛏️': ['bed', 'sleep'],
  '🛋️': ['couch', 'sofa'],
  '🪑': ['chair'],
  '🪠': ['plunger'],
  '🪒': ['razor'],
  '🧷': ['safety pin'],
  '🧹': ['broom', 'sweep'],
  '🧺': ['basket'],
  '🧻': ['toilet paper', 'roll'],
  '🧽': ['sponge'],
  '🛒': ['shopping cart'],
  '🚬': ['cigarette'],
  '⚰️': ['coffin'],
  '🪦': ['headstone', 'grave'],
  '🗿': ['moai', 'statue'],
  '🪩': ['mirror ball', 'disco'],
  '🎏': ['carp streamer'],
  '🎀': ['ribbon', 'bow'],
  '🪅': ['piñata'],

  // Travel
  '🚗': ['car', 'auto', 'vehicle'],
  '🚕': ['taxi'],
  '🚙': ['suv', 'recreational vehicle'],
  '🚌': ['bus'],
  '🚎': ['trolleybus'],
  '🏎️': ['racing car'],
  '🚓': ['police car'],
  '🚒': ['fire truck'],
  '🚐': ['minibus'],
  '🛻': ['pickup truck'],
  '🚚': ['delivery truck'],
  '🚛': ['articulated lorry'],
  '🚜': ['tractor'],
  '🛵': ['scooter'],
  '🏍️': ['motorcycle'],
  '🛺': ['auto rickshaw'],
  '🚲': ['bicycle', 'bike'],
  '🛴': ['kick scooter'],
  '🚁': ['helicopter'],
  '🛸': ['ufo'],
  '🛩️': ['small airplane'],
  '✈️': ['airplane', 'flight'],
  '🛬': ['airplane arriving'],
  '🛫': ['airplane departing'],
  '🪂': ['parachute'],
  '🚂': ['steam locomotive'],
  '🚃': ['railway car'],
  '🚄': ['high speed train'],
  '🚅': ['bullet train'],
  '🚆': ['train'],
  '🚇': ['metro', 'subway'],
  '🚈': ['light rail'],
  '🚉': ['station'],
  '🚊': ['tram'],
  '🛳️': ['passenger ship'],
  '⛴️': ['ferry'],
  '🚢': ['ship'],
  '⛵': ['sailboat'],
  '🚤': ['speedboat'],
  '🛥️': ['motor boat'],
  '⚓': ['anchor'],
  '🏠': ['house', 'home'],
  '🏡': ['house with garden'],
  '🏘️': ['houses'],
  '🏚️': ['derelict house'],
  '🏗️': ['building construction'],
  '🏢': ['office building'],
  '🏣': ['japanese post office'],
  '🏤': ['post office'],
  '🏦': ['bank'],
  '🏨': ['hotel'],
  '🏩': ['love hotel'],
  '🏪': ['convenience store'],
  '🏫': ['school'],
  '🏬': ['department store'],
  '🏭': ['factory'],
  '🏯': ['castle japanese'],
  '🏰': ['castle'],
  '💒': ['wedding chapel'],
  '🗼': ['tokyo tower'],
  '🗽': ['statue of liberty'],
  '⛪': ['church'],
  '🕌': ['mosque'],
  '🛕': ['hindu temple'],
  '🕍': ['synagogue'],
  '⛩️': ['shinto shrine'],
  '🕋': ['kaaba'],
  '⛲': ['fountain'],
  '⛺': ['tent', 'camping'],
  '🏕️': ['camping'],
  '🌁': ['foggy'],
  '🌃': ['night stars'],
  '🌆': ['cityscape dusk'],
  '🌇': ['sunset cityscape'],
  '🌉': ['bridge night'],
  '🗺️': ['world map'],
  '🧭': ['compass'],
  '🏝️': ['desert island'],

  // Flags (countries)
  '🇮🇩': ['indonesia', 'flag'],
  '🇺🇸': ['usa', 'united states', 'america', 'flag'],
  '🇬🇧': ['uk', 'united kingdom', 'britain', 'flag'],
  '🇯🇵': ['japan', 'flag'],
  '🇰🇷': ['korea', 'south korea', 'flag'],
  '🇨🇳': ['china', 'flag'],
  '🇫🇷': ['france', 'flag'],
  '🇩🇪': ['germany', 'flag'],
  '🇮🇹': ['italy', 'flag'],
  '🇪🇸': ['spain', 'flag'],
  '🇧🇷': ['brazil', 'flag'],
  '🇮🇳': ['india', 'flag'],
  '🇷🇺': ['russia', 'flag'],
  '🇨🇦': ['canada', 'flag'],
  '🇦🇺': ['australia', 'flag'],
  '🇲🇽': ['mexico', 'flag'],
  '🇹🇭': ['thailand', 'flag'],
  '🇻🇳': ['vietnam', 'flag'],
  '🇵🇭': ['philippines', 'flag'],
  '🇲🇾': ['malaysia', 'flag'],
  '🇸🇬': ['singapore', 'flag'],
  '🇳🇱': ['netherlands', 'holland', 'flag'],
  '🇸🇪': ['sweden', 'flag'],
  '🇳🇴': ['norway', 'flag'],
  '🇩🇰': ['denmark', 'flag'],
  '🇫🇮': ['finland', 'flag'],
  '🇵🇹': ['portugal', 'flag'],
  '🇦🇷': ['argentina', 'flag'],
  '🇨🇱': ['chile', 'flag'],
  '🇨🇴': ['colombia', 'flag'],
  '🇵🇪': ['peru', 'flag'],
  '🇪🇬': ['egypt', 'flag'],
  '🇿🇦': ['south africa', 'flag'],
  '🇳🇬': ['nigeria', 'flag'],
  '🇰🇪': ['kenya', 'flag'],
  '🇸🇦': ['saudi arabia', 'flag'],
  '🇦🇪': ['uae', 'emirates', 'flag'],
  '🇹🇷': ['turkey', 'flag'],
  '🇬🇷': ['greece', 'flag'],
  '🇵🇱': ['poland', 'flag'],
  '🇺🇦': ['ukraine', 'flag'],
  '🇳🇿': ['new zealand', 'flag'],
};

export default EMOJI_KEYWORDS;
